# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwaim < Formula
  desc "Git Worktree AI Manager — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/gwaim"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mdelapenya/gwaim/releases/download/v0.1.0/gwaim_darwin_amd64.tar.gz"
      sha256 "c3f7ccb0ef66e3e329dce58f543da82b48902cbb019a2f35884d76b5e5f9f421"

      define_method(:install) do
        bin.install "gwaim"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mdelapenya/gwaim/releases/download/v0.1.0/gwaim_darwin_arm64.tar.gz"
      sha256 "d10a4a3286be0f4d1624150ff6744f6ed267f892e8a503d1e36d01044a8abfdf"

      define_method(:install) do
        bin.install "gwaim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/gwaim/releases/download/v0.1.0/gwaim_linux_amd64.tar.gz"
      sha256 "b977fd73c3d6fb472de1b97553805fc09e8015274836734a40f2be2a2db5c8e0"
      define_method(:install) do
        bin.install "gwaim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mdelapenya/gwaim/releases/download/v0.1.0/gwaim_linux_arm64.tar.gz"
      sha256 "99d37473f7e295ce392591e44bbd96e7a83fb26637fa5c87e18f79cb76351ded"
      define_method(:install) do
        bin.install "gwaim"
      end
    end
  end
end
