# This file was generated by GoReleaser. DO NOT EDIT.
cask "biomelab-nightly" do
  version "0.3.0-nightly"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_amd64.tar.gz"
      sha256 "e46390e843f223b48854a076cc41ee4d6b605c74d3d0b930a72253741da85cde"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_arm64.tar.gz"
      sha256 "42d80559c5963983415945b78a5f0cfcc6ead91abd4d21b4c55eb2a5debd14f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_amd64.tar.gz"
      sha256 "687f5994375b7abe13dc73fb0a734d068d60e22dccb234776137f204ec2c1349"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_arm64.tar.gz"
      sha256 "36c7b811a4b45fe81cc076eec983173eac55db9fdf64ef293706f342dd063690"
    end
  end

  name "biomelab-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/biomelab"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "biomelab",
    ]

  binary "biomelab"

  # No zap stanza required

end
