# This file was generated by GoReleaser. DO NOT EDIT.
cask "biomelab" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_darwin_amd64.tar.gz"
      sha256 "7190f4753fda8bb13df4fc556f6c5f385d19f586ab872867bf57a7707cf84f25"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_darwin_arm64.tar.gz"
      sha256 "d6ad80b42e7f6356be70de348db07c680272fe6b5c2c59dd407c121adb0063f5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_linux_amd64.tar.gz"
      sha256 "c8b3e7aae5fececf05358bc970d791317f38f9cb51f8226c445060e9e7dd08e3"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_linux_arm64.tar.gz"
      sha256 "d41a325aaf3607aa2dc66124db1443795073e26fa7800bcd67f336ea8846921c"
    end
  end

  name "biomelab"
  desc "Git Worktree AI Manager — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/biomelab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "biomelab"

  # No zap stanza required

end
