# This file was generated by GoReleaser. DO NOT EDIT.
cask "biomelab-nightly" do
  version "0.3.0-nightly"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_amd64.tar.gz"
      sha256 "5c2a64bfde10070c3d76297229af5facc4075f08d851a7b82a3918f52167e0a8"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_arm64.tar.gz"
      sha256 "90c1e13138e46c03c392719d0f1806f88ec1da66d043e7cf74605aaa957f1a3a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_amd64.tar.gz"
      sha256 "2aadd5d2ed0fa89d71559ff4f91d3b1832dcacbbfd2eb0b853a3659dc781c59b"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_arm64.tar.gz"
      sha256 "ea3067a0623b02c2a6f80b6dfbf34909be480f6cd0e3360c8e99dec1aa8d993e"
    end
  end

  name "biomelab-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/biomelab"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "biomelab",
    ]

  binary "biomelab"

  # No zap stanza required

end
