# This file was generated by GoReleaser. DO NOT EDIT.
cask "biomelab-nightly" do
  version "0.3.0-nightly"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_amd64.tar.gz"
      sha256 "4ae619008f3ec92c3f788968deba1ecc89ed381f276bdc3cf0365e51c4e20901"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_darwin_arm64.tar.gz"
      sha256 "b9cf32e20e0f1ad04a6c3ae6a63133788ed8e9c0b3972d568e01b500c4b4b8c6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_amd64.tar.gz"
      sha256 "46affb0fd0c59565802dd0dedca22504b5970c2746e627d91b6a2bda63598c8c"
    end
    on_arm do
      url "https://github.com/mdelapenya/biomelab/releases/download/v#{version}/biomelab_#{version}_linux_arm64.tar.gz"
      sha256 "46aa88569b9ac6a92ef36663ee4407c16a569263fbc5294df7cc6029f19c4326"
    end
  end

  name "biomelab-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/biomelab"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "biomelab",
    ]

  binary "biomelab"

  # No zap stanza required

end
