# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwaim-nightly" do
  name "gwaim-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/gwaim"
  version "0.1.0-nightly-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwaim"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_darwin_amd64.tar.gz"
      sha256 "f71926cd709916fd4ee4ce3f9cd16a5885344a471fab3accaf77954885a9e960"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_darwin_arm64.tar.gz"
      sha256 "84e5454db990fabdf3f55e97b6a31c27fdf37f6ea76b8a84cb8d033136cc8d5c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_linux_amd64.tar.gz"
      sha256 "17125b38ea064381a0fed54ac58bf186713ab4aa4a4cd0809a2abb55e19a6f00"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_linux_arm64.tar.gz"
      sha256 "33d3607cabaa0ee29a3ca47727b135298f04e8f48a84567258de21348f0a228d"
    end
  end

  conflicts_with cask: [
      "gwaim",
    ]

  # No zap stanza required
end
