# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwaim-nightly" do
  name "gwaim-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/gwaim"
  version "0.1.0-nightly-nightly-nightly"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwaim"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_darwin_amd64.tar.gz"
      sha256 "855e8e02f418875834bf831a74adc3aa4657be1e9ac37aef2bcfdac62556aed8"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_darwin_arm64.tar.gz"
      sha256 "27c1342df5b2d66ee5d4ad3eca132bb8a9fba1c1969363d8e7d5c0a5f233e7f7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_linux_amd64.tar.gz"
      sha256 "dab1f3f36f33595ad02fea623af0f79ade6b10d2699869b37fe6c8a8eebd07c0"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_nightly_linux_arm64.tar.gz"
      sha256 "d4c4344ffc1a072d927c62731fab8f97c4d23ac908a6d468377fd6927c1b8f81"
    end
  end

  conflicts_with cask: [
      "gwaim",
    ]

  # No zap stanza required
end
