# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwaim-nightly" do
  version "0.1.0-nightly"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_#{version}_darwin_amd64.tar.gz"
      sha256 "46c78241ff5f5043b7a0766ad58e8d7eecb2034d76c0f9f8394d8a7c6596d2e2"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_#{version}_darwin_arm64.tar.gz"
      sha256 "d811a460602ec7513a1d2c25404ca893e6195b7be0639415ad13fd0b9885c521"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_#{version}_linux_amd64.tar.gz"
      sha256 "0ecf3daa869fa54c412ec2397e7d1fe3c69c55b5844a0c2e5ad1a9a6aaa7379b"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_#{version}_linux_arm64.tar.gz"
      sha256 "4a908fc761767e189ee14bc4d08d3fd2da679324e1e068f75dedd957bf147adc"
    end
  end

  name "gwaim-nightly"
  desc "Git Worktree AI Manager (nightly) — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/gwaim"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "gwaim",
    ]

  binary "gwaim"

  # No zap stanza required

end
