# This file was generated by GoReleaser. DO NOT EDIT.
cask "gwaim" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_darwin_amd64.tar.gz"
      sha256 "6939077384dc5f66e3fdd9e556f9737b5f5c04309eb1725884d67a1f63091311"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_darwin_arm64.tar.gz"
      sha256 "8c0a2c8056bdf52255e3c4c81c60143fa8e04e1dfd2b720a190faedd845385fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_linux_amd64.tar.gz"
      sha256 "6f59eeb176b45176a490377515f3375912894e46b822a5db5164b341999bd62c"
    end
    on_arm do
      url "https://github.com/mdelapenya/gwaim/releases/download/v#{version}/gwaim_linux_arm64.tar.gz"
      sha256 "9568d2badf0f7efd8059ed8a06320c49ebd77de25b75135325a4fa9c497192de"
    end
  end

  name "gwaim"
  desc "Git Worktree AI Manager — a terminal dashboard for git worktrees and coding agents"
  homepage "https://github.com/mdelapenya/gwaim"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gwaim"

  # No zap stanza required

end
